/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Nathan Gabriel
 */
public class Menu extends javax.swing.JFrame {

    public JButton getAtualizarCotacaoBtn() {
        return atualizarCotacaoBtn;
    }

    public void setAtualizarCotacaoBtn(JButton atualizarCotacaoBtn) {
        this.atualizarCotacaoBtn = atualizarCotacaoBtn;
    }

    public JButton getComprarCriptomoedasBtn() {
        return comprarCriptomoedasBtn;
    }

    public void setComprarCriptomoedasBtn(JButton comprarCriptomoedasBtn) {
        this.comprarCriptomoedasBtn = comprarCriptomoedasBtn;
    }

    public JButton getConsultarExtratoBtn() {
        return consultarExtratoBtn;
    }

    public void setConsultarExtratoBtn(JButton consultarExtratoBtn) {
        this.consultarExtratoBtn = consultarExtratoBtn;
    }

    public JButton getConsultarSaldoBtn() {
        return consultarSaldoBtn;
    }

    public void setConsultarSaldoBtn(JButton consultarSaldoBtn) {
        this.consultarSaldoBtn = consultarSaldoBtn;
    }

    public JButton getDepositarReaisBtn() {
        return depositarReaisBtn;
    }

    public void setDepositarReaisBtn(JButton depositarReaisBtn) {
        this.depositarReaisBtn = depositarReaisBtn;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JButton getSacarReaisBtn() {
        return sacarReaisBtn;
    }

    public void setSacarReaisBtn(JButton sacarReaisBtn) {
        this.sacarReaisBtn = sacarReaisBtn;
    }

    public JButton getSairBtn() {
        return sairBtn;
    }

    public void setSairBtn(JButton sairBtn) {
        this.sairBtn = sairBtn;
    }

    public JButton getVenderCriptomoedasBtn() {
        return venderCriptomoedasBtn;
    }

    public void setVenderCriptomoedasBtn(JButton venderCriptomoedasBtn) {
        this.venderCriptomoedasBtn = venderCriptomoedasBtn;
    }


    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consultarSaldoBtn = new javax.swing.JButton();
        consultarExtratoBtn = new javax.swing.JButton();
        venderCriptomoedasBtn = new javax.swing.JButton();
        comprarCriptomoedasBtn = new javax.swing.JButton();
        depositarReaisBtn = new javax.swing.JButton();
        sacarReaisBtn = new javax.swing.JButton();
        atualizarCotacaoBtn = new javax.swing.JButton();
        sairBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Menu");

        consultarSaldoBtn.setText("Consultar saldo");

        consultarExtratoBtn.setText("Consultar extrato");

        venderCriptomoedasBtn.setText("Vender criptomoedas");

        comprarCriptomoedasBtn.setText("Comprar criptomoedas");

        depositarReaisBtn.setText("Depositar reais");

        sacarReaisBtn.setText("Sacar reais");

        atualizarCotacaoBtn.setText("Atualizar cotação");

        sairBtn.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarExtratoBtn)
                            .addComponent(consultarSaldoBtn)
                            .addComponent(depositarReaisBtn)
                            .addComponent(sacarReaisBtn)
                            .addComponent(comprarCriptomoedasBtn)
                            .addComponent(venderCriptomoedasBtn)
                            .addComponent(atualizarCotacaoBtn)
                            .addComponent(sairBtn))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(consultarSaldoBtn)
                .addGap(18, 18, 18)
                .addComponent(consultarExtratoBtn)
                .addGap(18, 18, 18)
                .addComponent(depositarReaisBtn)
                .addGap(18, 18, 18)
                .addComponent(sacarReaisBtn)
                .addGap(18, 18, 18)
                .addComponent(comprarCriptomoedasBtn)
                .addGap(18, 18, 18)
                .addComponent(venderCriptomoedasBtn)
                .addGap(18, 18, 18)
                .addComponent(atualizarCotacaoBtn)
                .addGap(18, 18, 18)
                .addComponent(sairBtn)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarCotacaoBtn;
    private javax.swing.JButton comprarCriptomoedasBtn;
    private javax.swing.JButton consultarExtratoBtn;
    private javax.swing.JButton consultarSaldoBtn;
    private javax.swing.JButton depositarReaisBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sacarReaisBtn;
    private javax.swing.JButton sairBtn;
    private javax.swing.JButton venderCriptomoedasBtn;
    // End of variables declaration//GEN-END:variables
}
